= Schedule I Mods

A collection of tiny mods to tweak to the gameplay experience.

== Mods

=== link:CopHealthModifier/[Cop Health Modifier]

Adds a configurable multiplier value to adjust police max health.

[none]
* On Nexus Mods: https://www.nexusmods.com/schedule1/mods/1691


=== link:DayLengthModifier/[Day Length Modifier]

Adds a configurable multiplier value to adjust game day length.

[none]
* *Not currently published to mod sites* due to significant similarity with one or
more existing, functional mods.


=== link:DisableDealBonuses/[Disable Deal Bonuses]

Removes the bonus payments on deals for quality, curfew, quick delivery, and
weather.

[none]
* On Nexus Mods: https://www.nexusmods.com/schedule1/mods/1708


=== link:DisableDealBonuses/[Disable Hotbar Scroll]

Disables the mouse wheel interaction with the inventory hotbar.

[none]
* On Nexus Mods: https://www.nexusmods.com/schedule1/mods/1739

=== link:DonutMixFix/[Donut Mixing Fix]

Corrects the mixing interaction with `CalorieDense + CalorieDense`.

[none]
* On Nexus Mods: https://www.nexusmods.com/schedule1/mods/1604


=== link:GrowthSpeedModifier/[Plant Growth Modifiers]

Adds configurable multiplier values to adjust the growth speed of different
plant types.

[none]
* *Not currently published to mod sites* due to significant similarity with one or
more existing, functional mods.


=== link:GunControl/[Gun Control]

Marks guns and ammunition as illegal.

[none]
* On Nexus Mods: https://www.nexusmods.com/schedule1/mods/1657


=== link:IllegalSeeds/[Illegal Seeds]

Marks coca and marijuana seeds as illegal.

[none]
* On Nexus Mods: https://www.nexusmods.com/schedule1/mods/1663


=== link:ObservantCops/[Observant Cops]

Makes cops notice when the player is openly holding an illegal item.

[none]
* On Nexus Mods: https://www.nexusmods.com/schedule1/mods/1677


=== link:RecommendedPrice/[Recommended Price]

Adds configurable multiplier values to adjust the market price of the different
drug types.

[none]
* On Nexus Mods: https://www.nexusmods.com/schedule1/mods/1654


=== link:TrashCanCapacity/[Trash Can Capacity]

Adjust trash can capacity.

[none]
* On Nexus Mods: https://www.nexusmods.com/games/schedule1/mods/1745
